use quote::quote;
use std::{
    fs,
    process::{Command, Stdio},
};

fn main() {
    let node_version_path = ".node-version";
    let node_version = fs::read_to_string(node_version_path)
        .expect("Failed to read .node-version")
        .trim()
        .to_string();

    // Get Node.js major version
    let node_major_version = node_version.split('.').next().unwrap();

    println!("Using Node.js version: {node_version}");

    // Run Node.js command to get built-in modules
    let output = Command::new("node")
        .arg("-p")
        .arg("[...require('module').builtinModules].map(b => JSON.stringify(b)).join(',\\n')")
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output()
        .expect("Failed to execute node command");

    if !output.status.success() {
        eprintln!("Node.js command failed:");
        eprintln!("{}", String::from_utf8_lossy(&output.stderr));
        std::process::exit(1);
    }

    let modules_output = String::from_utf8(output.stdout).expect("Invalid UTF-8 output");

    // Parse the module names (they're JSON strings separated by commas and newlines)
    let json_array_str = format!("[{}]", modules_output.trim());
    let all_modules: Vec<String> =
        serde_json::from_str(&json_array_str).expect("Failed to parse module list");

    // Separate modules with mandatory node: prefix from regular modules
    let mut mandatory_prefix_modules: Vec<String> = all_modules
        .iter()
        .filter(|m| m.starts_with("node:"))
        .map(|m| m.strip_prefix("node:").unwrap().to_string())
        .collect();
    mandatory_prefix_modules.sort();

    let mut regular_modules: Vec<String> = all_modules
        .iter()
        .filter(|m| !m.starts_with("node:"))
        .cloned()
        .collect();
    regular_modules.sort();

    // Build the complete file with doc comments using quote!
    let regular_module_refs = &regular_modules;
    let mandatory_module_refs = &mandatory_prefix_modules;

    let content = format!(
        r#"//! Node.js v{} built-in modules
//!
//! <https://nodejs.org/api/modules.html#built-in-modules>

/// Generated by
///
/// `node -p "[...require('module').builtinModules].map(b => JSON.stringify(b)).join(',\n')"`
///
/// with `node:` prefixed values moved [BUILTINS_WITH_MANDATORY_NODE_PREFIX].
{}

/// <https://nodejs.org/api/modules.html#built-in-modules-with-mandatory-node-prefix>
{}

/// Is `specifier` a node.js built-in module?
{}
"#,
        node_major_version,
        quote! { pub static BUILTINS: &[&str] = &[#(#regular_module_refs,)*]; },
        quote! { pub static BUILTINS_WITH_MANDATORY_NODE_PREFIX: &[&str] = &[#(#mandatory_module_refs),*]; },
        quote! {
            pub fn is_nodejs_builtin_module(specifier: &str) -> bool {
                if let Some(stripped) = specifier.strip_prefix("node:") {
                    return BUILTINS.contains(&stripped)
                        || BUILTINS_WITH_MANDATORY_NODE_PREFIX.contains(&stripped);
                }
                BUILTINS.contains(&specifier)
            }
        }
    );

    // Write to src/lib.rs
    fs::write("src/lib.rs", content).expect("Failed to write src/lib.rs");

    println!("✓ Updated built-in modules for Node.js v{node_version}");
    println!("  - {} regular modules", regular_modules.len());
    println!(
        "  - {} mandatory prefix modules",
        mandatory_prefix_modules.len()
    );
}
