name: Update Built-in Modules

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main
    paths:
      - .node-version
      - .github/workflows/update-builtins.yml
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  update-builtins:
    name: Update Node.js Built-in Modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: true
          token: ${{ steps.app-token.outputs.token }}

      - uses: voidzero-dev/setup-vp@250f29ce396baf5e8f24498e17c0dfdebabc26eb # v1.15.0
        with:
          node-version-file: .node-version
          run-install: false

      - uses: oxc-project/setup-rust@3d6fb132fbe7cdcb66bf8ec193911c2945369d12 # v1.0.17
        with:
          components: rustfmt

      - run: cargo run -p update_builtins

      - run: cargo fmt

      - run: cargo test

      - uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          commit_message: "chore: update built-in modules for Node.js ${{ steps.node-version.outputs.version }} [skip ci]"
          file_pattern: src/lib.rs
